openapi: "3.0.0"
info:
  version: 1.0.0
  title: Product Service
servers:
  - url: http://localhost:8080
paths:
  /product/hello:
    get:
      summary: Gets Hello World
      operationId: hello
      tags:
        - hello
      responses:
        '200':
          description: Hello World
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"
components:
  schemas:
    Greeting:
      required:
        - text
      properties:
        text:
          type: string