server:
  servlet:
    context-path: "/api/service-name"
  error:
    whitelabel:
      enabled: off

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: on
  sql:
    init:
      mode: always

management:
  health:
    db:
      enabled: true
  endpoint:
    info:
      enabled: on
