server:
  servlet:
    context-path: ""
  error:
    whitelabel:
      enabled: off
spring:
  datasource:
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: "*"