/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.andino.service;


import org.andino.catalyst.Printer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CatalystApplication {

    public static void main(String[] args) {
        System.out.println(new Printer("Whatever"));
        SpringApplication.run(CatalystApplication.class, args);
    }

}
