spring:
  datasource:
    #url value will get either from environment variables or from config server
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    locations: classpath:/db/migration
    enabled: on
  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: validate
    generate-ddl: off