/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.andino.service;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.modulith.core.ApplicationModules;
import org.springframework.modulith.docs.Documenter;

@SpringBootTest
class CatalystApplicationTests {

    ApplicationModules modules = ApplicationModules.of(CatalystApplication.class);

    @Test
    void contextLoads() {
    }

    @Test
    void writeDocumentationSnippets() {
        new Documenter(modules)
                .writeModulesAsPlantUml()
                .writeIndividualModulesAsPlantUml();
        new Documenter(modules)
                .writeModuleCanvases();
    }

}
