/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.andino.service;

import org.andino.service.shared.PostgreSQLContainer;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.modulith.core.ApplicationModules;
import org.springframework.modulith.docs.Documenter;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase.Replace.NONE;

@SpringBootTest
@Testcontainers
@AutoConfigureTestDatabase(replace = NONE)
@PostgreSQLContainer
class CatalystApplicationTests {

	ApplicationModules modules = ApplicationModules.of(CatalystApplication.class);

	@Test
	void contextLoads() {
		modules.verify();
	}

	@Test
	void writeDocumentationSnippets() {
		new Documenter(modules).writeModulesAsPlantUml().writeIndividualModulesAsPlantUml();
		new Documenter(modules).writeModuleCanvases();
	}

}
