/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.andino.service;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class CatalystApplicationTests {

    @Test
    void contextLoads() {
    }

}
